Delete act steps
Because of:
Error: reusable workflows are currently not supported (see https://github.com/nektos/act/issues/826 for updates)

Act does not support our workflow structure

Signed-off-by: Christian Zunker <christian@mondoo.com>